#!/usr/bin/env python

PPS_INPUT_GPIO = -1         # 0-31. Use -1 for inactive
PPS_OUTPUT_GPIO = 2         # 0-31. Use -1 for inactive
PPS_OUTPUT_DUTY = 0.2       # Fractional duty cycle

TRIGGER1_GPIO = 3           # 0-31. Use -1 for inactive
TRIGGER2_GPIO = 4
TRIGGER3_GPIO = 5
TRIGGER4_GPIO = 6
TRIGGER5_GPIO = 7
TRIGGER6_GPIO = 8

TRIGGER1_FREQUENCY = 10     # Integer number in Hertz
TRIGGER2_FREQUENCY = 10
TRIGGER3_FREQUENCY = 10
TRIGGER4_FREQUENCY = 10
TRIGGER5_FREQUENCY = 10
TRIGGER6_FREQUENCY = 10

TRIGGER1_PHASE = 0          # 0-360 in degrees
TRIGGER2_PHASE = 0
TRIGGER3_PHASE = 0
TRIGGER4_PHASE = 0
TRIGGER5_PHASE = 0
TRIGGER6_PHASE = 0

TRIGGER1_DUTY = 0.5         # Fractional duty cycle
TRIGGER2_DUTY = 0.5
TRIGGER3_DUTY = 0.5
TRIGGER4_DUTY = 0.5
TRIGGER5_DUTY = 0.5
TRIGGER6_DUTY = 0.5

USE_SYNC = False
if PPS_INPUT_GPIO > 0:
    USE_SYNC = True         # Enable synchronization to PPS input when available

SEND_DUMMY_NMEA = False     # Enable spoof NMEA messages
NMEA_DESTINATION_PORT = 10110
NMEA_DESTINATION_HOST = '192.168.1.201'

TRIGGER_GPIOS = [TRIGGER1_GPIO, TRIGGER2_GPIO, TRIGGER3_GPIO,
                    TRIGGER4_GPIO, TRIGGER5_GPIO, TRIGGER6_GPIO]

TRIGGER_FREQUENCIES = [TRIGGER1_FREQUENCY, TRIGGER2_FREQUENCY, TRIGGER3_FREQUENCY,
                        TRIGGER4_FREQUENCY, TRIGGER5_FREQUENCY, TRIGGER6_FREQUENCY]

TRIGGER_PHASES = [TRIGGER1_PHASE, TRIGGER2_PHASE, TRIGGER3_PHASE,
                    TRIGGER4_PHASE, TRIGGER5_PHASE, TRIGGER6_PHASE]

TRIGGER_DUTYS = [TRIGGER1_DUTY, TRIGGER2_DUTY, TRIGGER3_DUTY,
                    TRIGGER4_DUTY, TRIGGER5_DUTY, TRIGGER6_DUTY]
